dataset: [restaurants, flipkart] # [restaurants, flipkart, bygghemma]
modalities: [numerical] # numerical, binary, categorical
metric: recall # r_precision, recall
num_results: [10] # set to [] to return the maximum number of results
num_repetitions: 10
# Only used with numerical modalities
num_harmonics: [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
interval_epsilon: [0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03]