dataset: [restaurants, flipkart] # [restaurants, flipkart]
modalities: numerical # numerical, binary, categorical
#experiment: faiss # faiss, truth
num_repetitions: 10
num_results: 10
harmonics: [50, 100, 150, 200, 250, 300, 350, 400, 450, 500] # only used with numerical modalities
interval_epsilon: [0.0, 0.01, 0.015, 0.2, 0.25, 0.3] # only used with numerical modalities